---
apiVersion: k8s-app-runner.aubm.net/v1
kind: Application
metadata:
  name: hello-from-python
spec:
  runtime: 'python3'
  port: 5000
  entrypoint: 'app.py'
  env:
    - name: 'HELLO_TO'
      value: 'Python experts'
  source:
    git:
      gitRepositoryUrl: 'https://github.com/aubm/k8s-app-runner.git'
      revision: 'b47fdd6e96135f937ac4d242ca1ebb3a78c9c354'
      root: 'sample-apps/hello-python'
---
apiVersion: k8s-app-runner.aubm.net/v1
kind: Application
metadata:
  name: hello-from-node
spec:
  runtime: 'node14'
  port: 3000
  entrypoint: 'app.js'
  env:
    - name: 'HELLO_TO'
      value: 'Node experts'
  source:
    git:
      gitRepositoryUrl: 'https://github.com/aubm/k8s-app-runner.git'
      root: 'sample-apps/hello-node'

