apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: k8s-app-runner-system
namePrefix: k8s-app-runner-

resources:
  - crd.yaml
  - manisfests.yaml

secretGenerator:
  - name: controller-manager-tls
    files:
      - pki/tls.crt
      - pki/tls.key
    type: "kubernetes.io/tls"

configurations:
  - kustomizeconfig.yaml
